<a href="https://colab.research.google.com/github/ShahadatKabir/hsc_math_with_python/blob/master/Matrix_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
Matrix= np.array([[0,1,2],
                  [4,4,5],
                  [6,7,4]])
print(f" total_element = {Matrix.size}")
print(f"dimension = {Matrix.shape}")

print(f"row = {Matrix.shape[0]} and column ={Matrix.shape[1]} ")
Entry_postion= np.where(Matrix ==4)
print(Entry_postion)

print(f"row index {Entry_postion[0][0]} column index {Entry_postion[1][0]}")

 total_element = 9
dimension = (3, 3)
row = 3 and column =3 
(array([1, 1, 2]), array([0, 1, 2]))
row index 1 column index 0


In [ ]:
Matrix1=np.array([[2,3,4],
                  [5,6,7],
                  [8,5,6]])
print(f"totla_element={Matrix1.size}")

print(f"dimension ={Matrix1.shape}")

print(f"row ={Matrix1.shape[0]} and column ={Matrix1.shape[1]}")

Entry_position1 =np.where(Matrix1==8)

print(Entry_position1)

print(f"row index {Entry_position1[0][0]} column index {Entry_position1 [1][0]}")


totla_element=9
dimension =(3, 3)
row =3 and column =3
(array([2]), array([0]))
row index 2 column index 0


In [ ]:
Matrix2=np.array([[6,3,5],
                  [7,8,9],
                  [10,11,13]])

print(f"total_element={Matrix2.size}")

print(f"dimension ={Matrix2.shape}")

print(f"row ={Matrix2.shape[0]} and column ={Matrix2.shape[1]}")

Entry_position2 =np.where(Matrix2==13)

print(Entry_position2)

print(f"row index {Entry_position2[0][0]} column index {Entry_position2 [1][0]}")

total_element=9
dimension =(3, 3)
row =3 and column =3
(array([2]), array([2]))
row index 2 column index 2


In [ ]:
Matrix3=np.array([[3,4,5],
                  [77,44,55],
                  [99,44,55]])
print(f"totlat_element={Matrix3.size}")

print(f"Dimension3={Matrix3.shape}")

print(f"row ={Matrix3.shape[0]} and column ={Matrix3.shape[1]} ")

Find_position =np.where(Matrix3==44)

print(Find_position)

print(f"row index {Find_position[0][0]} and column index {Find_position[1][0]}")

totlat_element=9
Dimension3=(3, 3)
row =3 and column =3 
(array([1, 2]), array([1, 1]))
row index 1 and column index 1
